### ISSUE TITLE
argparse does not allow multicharacter short args that overlap a shorter argument, e.g. "-R" and "-RMQT" conflict

### ISSUE THREAD

**Issue by vyellapa** [mskcc/cmo#9]
When parsing arguments which is a subset of other arguments, cmo_gatk throws an error.

Example:
When running a command like:
cmo_gatk -T SplitNCigarReads -R GRCh37 -I dedupped.bam -o split.bam -rf ReassignOneMappingQuality -RMQF 255 -RMQT 60 -U ALLOW_N_CIGAR_READS

I get an error:
cmo_gatk: error: argument -R/--reference_sequence: invalid choice: 'MQF' (choose from u'GRCm38', u'ncbi36', u'mm9', u'GRCh37', u'GRCh38', u'hg18', u'hg19', u'mm10')

**Comment by lordzappo** [comment]
It seems that python's argparse really wants to make -RMQF map to -R due to
the way short args and long args work.

For your immediate purpose, spelling out the filter arguments should be a
viable workaround.

cmo_gatk -T SplitNCigarReads -R GRCh37 -I dedupped.bam -o split.bam -rf
ReassignOneMappingQuality --reassign_mapping_quality_from  255
--reassign_mapping_quality_to 60 -U ALLOW_N_CIGAR_READS
WARNING: INCLUDING UNKNOWN ARGUMENTS (DID YOU TYPO, OR IS THIS A WEIRD
COLON ARGUMENT THAT GATK SUCKS FOR HAVING?
--reassign_mapping_quality_from 255 --reassign_mapping_quality_to 60

...

## INFO  13:22:45,911 HelpFormatter -

INFO  13:22:45,913 HelpFormatter - The Genome Analysis Toolkit (GATK)
v3.4-0-g7e26428, Compiled 2015/05/15 03:25:41
INFO  13:22:45,913 HelpFormatter - Copyright (c) 2010 The Broad Institute
INFO  13:22:45,913 HelpFormatter - For support and documentation go to
http://www.broadinstitute.org/gatk
INFO  13:22:45,916 HelpFormatter - Program Args: -T SplitNCigarReads
--reassign_mapping_quality_to 60 --input_file dedupped.bam
--reassign_mapping_quality_from 255 --unsafe ALLOW_N_CIGAR_READS
--read_filter ReassignOneMappingQuality --reference_sequence
/ifs/depot/assemblies/H.sapiens/b37/b37.fasta --out split.bam

**Comment by lordzappo** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10211964-132012173_2-s1-v1.png?transparent=1&width=246)

**Comment by lordzappo** [comment]
This is an argparse "feature":

For short options (options only one character long), the option and its value can be concatenated:

> > > parser.parse_args(['-xX'])
> > > Namespace(foo=None, x='X')

So, this will happen for sure on any argument that matches a one character short arg that takes a value.

I won't close this ticket but I'm not sure a fix is possible at this point in time, need to look some more.

**Comment by ckandoth** [comment]
Fix not possible.
